# version: "3.9"  # Specify the version of the Docker Compose file

services:
  streamlit:
    build:
      context: ./            # Specify the build context (where the Dockerfile is located)
      dockerfile: ./Dockerfile # Path to your Dockerfile (ensure the filename is lowercase if not standard)
    ports:
      - "8501:8501"          # Map host port 8081 to container port 8501 (Streamlit's default port)
